// Generated by CoffeeScript 1.6.3
(function() {
  var mediaObj;

  window.h5media = function(selector) {
    return new mediaObj(selector);
  };

  mediaObj = function(selector) {
    this.selector = document.querySelector(selector);
    return this;
  };

  mediaObj.prototype = {
    hasGetUserMedia: function() {
      return navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigatoroGetUserMedia || navigator.msieGetUserMedia || false;
    },
    openVideo: function() {
      var selector;
      selector = this.selector;
      if (this.hasGetUserMedia(this.selector)) {
        navigator.getUserMedia = this.hasGetUserMedia(this.selector);
        navigator.getUserMedia({
          video: true
        }, function(mediaStream) {
          return selector.src = window.URL.createObjectURL(mediaStream);
        }, function(error) {
          return error;
        });
      } else {
        return false;
      }
      return true;
    },
    pauseVideo: function(container) {
      return container.pause();
    }
  };

}).call(this);
