// Generated by CoffeeScript 1.6.3
(function() {
  var mediaObj;

  window.h5media = function(selector) {
    return new mediaObj(selector);
  };

  mediaObj = function(selector) {
    this.selector = selector;
    this.stream = null;
    return this;
  };

  mediaObj.prototype = {
    hasGetUserMedia: function() {
      return navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigatoroGetUserMedia || navigator.msieGetUserMedia || false;
    },
    openVideo: function() {
      var th;
      th = this;
      if (this.hasGetUserMedia(this.selector)) {
        navigator.getUserMedia = this.hasGetUserMedia(this.selector);
        navigator.getUserMedia({
          video: true
        }, function(mediaStream) {
          th.selector.src = (window.URL || window.webkitURL).createObjectURL(mediaStream);
          th.stream = mediaStream;
          return th;
        }, function(error) {
          return error;
        });
      } else {
        return false;
      }
      return true;
    },
    pauseVideo: function() {
      this.selector.pause();
      return this.stream.stop();
    },
    resumeVideo: function() {
      return this.openVideo();
    },
    closeVideo: function() {
      this.pauseVideo();
      return this.selector.src = "";
    }
  };

}).call(this);
